### ISSUE TITLE
Interpret plotly animations into the html

### ISSUE THREAD

**Issue by JavierCladellas** [feelpp/feelpp-asciidoctor-extensions#17]
If a plotly figure contains frames, the `%raw` argument does not display the figure. 
Although, currently the animation appears when `%raw` is not present. It would by useful when dynamically generating multiple figure/animation combinations. 

A css workaround to make the animation appear like  other figures (does not fix the `%raw` compatibility)

```css
<style>
details>.title::before, details>.title::after {
    visibility: hidden;
}

#_solar_shading + .listingblock + details>.content>.dynamic-py-result>.content>pre {
    max-height: 100%;
    padding: 0;
    background-color: white;
}

#_solar_shading + details>.content>.dynamic-py-result>.content>pre {
    max-height: 100%;
    padding: 0;
    background-color: white;
}

</style>
```
